### ISSUE TITLE
The Google Chrome browser detects the cloudflare shield, but the browser automatically closes when running.

### ISSUE THREAD

**Issue by 7161457** [AeonLucid/FlareSolverr#1]
![1670315137173](https://user-images.githubusercontent.com/113887555/205860861-0febdfa7-180e-424a-8b87-6cd478435595.jpg)
![1670315486027](https://user-images.githubusercontent.com/113887555/205860869-b026fb54-85cd-4489-b5ff-7157f315a519.jpg)
![1670315525124](https://user-images.githubusercontent.com/113887555/205860871-3eaafa3d-bd6c-4ed3-8f6c-430b592d0dd3.jpg)
The status code is 200, but the web page has not actually entered. The browser automatically closes when it passes the CloudFlare Shield.

**Comment by AeonLucid** [comment]
Please run with `LOG_LEVEL` debug. You tried to do this but you forgot to put `export`. Post a new log.

I notice you are sending cookies, this is currently not supported in `3.0.0`.

**Comment by AeonLucid** [comment]
I have added support for cookies, please pull the repository and try again.

https://github.com/AeonLucid/FlareSolverr/commit/50077f840b4a602c8d0b27c9434aab419291f474

Cookies need to be formatted as follows: https://vanilla.aslushnikov.com/?Network.setCookie.

**Comment by 7161457** [comment]
I'm using this website（ https://vanilla.aslushnikov.com/?Network.setCookie ）When splitting cookies, I encountered difficulties. I don't understand the format. Please help me to split cookies. This is my cookies (c_secure_uid=MTIxOTA% 3D; c_secure_pass=78fca7358246364ff4cfdeb0d6acfb70; c_secure_ssl=eWVhaA% 3D% 3D; c_secure_tracker_ssl=eWVhaA% 3D% 3D; c_secure_login=bm9wZQ% 3D% 3D; cf_clearance=e9e07a7d37c005206549acd15416866e62dcb3cc-16671802272-0-150). I am the website（ https://wintersakura.net/attendance.php ）

**Comment by 7161457** [comment]
One good news and one bad news.The good news is that you can run it 20 times and succeed once.  The bad news is The remaining 19 times are all such error prompts.
![1670409936102](https://user-images.githubusercontent.com/113887555/206164561-50952963-410d-4930-9c30-9cf050fedb5a.jpg)
![1670410025726](https://user-images.githubusercontent.com/113887555/206164576-a88b1c34-a306-445f-b7c6-74431718ec9b.jpg)
![1670410047588](https://user-images.githubusercontent.com/113887555/206164583-71260389-d221-424b-a434-3aa08f32c052.jpg)

**Comment by 7161457** [comment]
Another case is that the URL can be accessed normally, but no data has been returned, resulting in timeout failure
![1670412662416](https://user-images.githubusercontent.com/113887555/206169220-1684999d-9c7e-425c-9829-d31392d8a751.jpg)
![1670412713087](https://user-images.githubusercontent.com/113887555/206169246-f8fbc10c-80ca-43c4-88af-3cd43f2a96dc.jpg)
![1670412768739](https://user-images.githubusercontent.com/113887555/206169259-f4cf168d-1812-4e47-a329-76c5bffc3ff7.jpg)
![1670412780431](https://user-images.githubusercontent.com/113887555/206169271-99cb2dc0-4778-4f84-be25-dba2edc6ff1b.jpg)

**Comment by 7161457** [comment]
Good news. I can run normally after debugging. I look forward to your official release https://hub.docker.com/

**Comment by AeonLucid** [comment]
> Good news. I can run normally after debugging. I look forward to your official release https://hub.docker.com/

What was the issue? I saw your previous comments which are now removed.

**Comment by 7161457** [comment]
> 

The previous problem is the cookies of Windows browser, which will fail in Linux. I have successfully solved it.

**Comment by 7161457** [comment]
Hello, I found a new problem today. There are 3 problems in total, which are described in detail below.

1.From source code can be used normally. All Docker versions cannot be used normally. The following error will occur.
The website does not use the status of cookies when logging in.
![1670573628542](https://user-images.githubusercontent.com/113887555/206660043-9517d34d-0cdc-4719-9334-0d6a9d34eb8f.jpg)
![1670573630057](https://user-images.githubusercontent.com/113887555/206660052-76dbfce4-0981-400b-a42d-f07b704a9b85.jpg)
![1670573758235](https://user-images.githubusercontent.com/113887555/206660056-530f7b4e-5ff8-46eb-8790-cdca87c7b6e0.jpg)


2.When the From source code is used, the target website has been successfully loaded, but FlareSolver does not return data, resulting in maxTimeout waiting for timeout to close
![1](https://user-images.githubusercontent.com/113887555/206660572-c3a5bd6f-9f5e-4735-9d06-5e96b9cb5700.jpg)
![11](https://user-images.githubusercontent.com/113887555/206660596-fd3513c6-5cda-43d8-9085-ef00c557071f.jpg)
![111](https://user-images.githubusercontent.com/113887555/206660598-2a1f65ac-824c-41d8-9f10-ea8c1ec34f49.jpg)
![1111](https://user-images.githubusercontent.com/113887555/206660605-8cbb8cfd-f291-4878-b8ac-28640db41390.jpg)
![11111](https://user-images.githubusercontent.com/113887555/206660610-7d2b431a-1d1c-430d-9ff6-c907d4d15eb0.jpg)


3.When using the source code, the following errors will occur today for websites that can be accessed normally yesterday.
![2](https://user-images.githubusercontent.com/113887555/206660956-abaffb90-47c5-48e4-9426-e96d5a63a36a.jpg)
![22](https://user-images.githubusercontent.com/113887555/206660966-5819cc82-9370-4934-a811-109ce5b82e90.jpg)
![222](https://user-images.githubusercontent.com/113887555/206660968-40280c23-76b1-4d5b-8f48-cdf40d1505db.jpg)
